CREATE TABLE permitful_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

ALTER TABLE permitful_favorites
    ADD COLUMN
        user_id INTEGER REFERENCES permitful_users(id)
        ON DELETE SET NULL;